# ethernet
CONNECTION_0_POINT_0_BW=10gbps
CONNECTION_0_POINT_0_LT=2ms

CONNECTION_0_POINT_1_BW=10gbps
CONNECTION_0_POINT_1_LT=2ms

# ethernet
CONNECTION_1_POINT_0_BW=10gbps
CONNECTION_1_POINT_0_LT=2ms

CONNECTION_1_POINT_1_BW=10gbps
CONNECTION_1_POINT_1_LT=2ms
