# ethernet
CONNECTION_0_POINT_0_BW=10gbps
CONNECTION_0_POINT_0_LT=1ms

CONNECTION_0_POINT_1_BW=10gbps
CONNECTION_0_POINT_1_LT=1ms

# ethernet
CONNECTION_1_POINT_0_BW=10gbps
CONNECTION_1_POINT_0_LT=1ms

CONNECTION_1_POINT_1_BW=10gbps
CONNECTION_1_POINT_1_LT=1ms
