# wifi 2.4g
CONNECTION_0_POINT_0_BW=12mbps
CONNECTION_0_POINT_0_LT=10ms

CONNECTION_0_POINT_1_BW=12mbps
CONNECTION_0_POINT_1_LT=10ms

# wifi 2.4g
CONNECTION_1_POINT_0_BW=12mbps
CONNECTION_1_POINT_0_LT=10ms

CONNECTION_1_POINT_1_BW=12mbps
CONNECTION_1_POINT_1_LT=10ms
