# wifi 2.4g
CONNECTION_0_POINT_0_BW=12mbps
CONNECTION_0_POINT_0_LT=2ms

CONNECTION_0_POINT_1_BW=12mbps
CONNECTION_0_POINT_1_LT=2ms

# acoustic
CONNECTION_1_POINT_0_BW=1mbps
CONNECTION_1_POINT_0_LT=50ms

CONNECTION_1_POINT_1_BW=1mbps
CONNECTION_1_POINT_1_LT=50ms
