version: "2.4"
services:

    bw_server0: &server
        image: docker.io/chaos-whoi/whoi-slocum-adaptive-networking:master-amd64
        environment:
            CPK_LAUNCHER: bw-server
        privileged: true
        network_mode: container:ppp00

    bw_client0: &client
        image: docker.io/chaos-whoi/whoi-slocum-adaptive-networking:master-amd64
        depends_on:
            -   bw_server0
        environment:
            CPK_LAUNCHER: bw-client
            SERVER_HOST: 10.0.0.1
        privileged: true
        network_mode: container:ppp01

    bw_server1:
        <<: *server
        network_mode: container:ppp10

    bw_client1:
        <<: *client
        depends_on:
            -   bw_server1
        environment:
            CPK_LAUNCHER: bw-client
            SERVER_HOST: 10.0.1.1
        network_mode: container:ppp11
