version: "2.4"
services:

    # computer 0

    tc00: &tc0
        image: docker.io/chaos-whoi/whoi-slocum-adaptive-networking:master-amd64
        environment:
            CPK_LAUNCHER: tc-on-ppp
            DEVICE: ppp0
            BANDWIDTH: ${CONNECTION_0_POINT_0_BW:-10gbps}
            LATENCY: ${CONNECTION_0_POINT_0_LT:-0ms}
        privileged: true
        network_mode: container:computer0

    tc10: &tc1
        image: docker.io/chaos-whoi/whoi-slocum-adaptive-networking:master-amd64
        environment:
            CPK_LAUNCHER: tc-on-ppp
            DEVICE: ppp1
            BANDWIDTH: ${CONNECTION_1_POINT_0_BW:-10gbps}
            LATENCY: ${CONNECTION_1_POINT_0_LT:-0ms}
        privileged: true
        network_mode: container:computer0


    # computer 1

    tc01:
        <<: *tc0
        environment:
            CPK_LAUNCHER: tc-on-ppp
            DEVICE: ppp0
            BANDWIDTH: ${CONNECTION_0_POINT_1_BW:-10gbps}
            LATENCY: ${CONNECTION_0_POINT_1_LT:-0ms}
        network_mode: container:computer1

    tc11:
        <<: *tc1
        environment:
            CPK_LAUNCHER: tc-on-ppp
            DEVICE: ppp1
            BANDWIDTH: ${CONNECTION_1_POINT_1_BW:-10gbps}
            LATENCY: ${CONNECTION_1_POINT_1_LT:-0ms}
        network_mode: container:computer1
